"use client";

import { useMemo, useState } from "react";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { ArrowRight, Bot, BriefcaseBusiness, Building2, Check, CheckCircle2, GraduationCap, Search, ShieldCheck, Sparkles, Target, Users } from "lucide-react";

const transition = { duration: .24 };
export function ProductExperience() {
  const [step, setStep] = useState(0); const reduced = useReducedMotion();
  const steps = [
    { title: "Set the outcome", text: "Land a product role by October", icon: Target },
    { title: "Generate the roadmap", text: "AI creates milestones, risks and weekly actions", icon: Sparkles },
    { title: "Execute with context", text: "Tasks adapt as your real life changes", icon: CheckCircle2 },
    { title: "Build momentum", text: "Progress, memory and opportunities stay connected", icon: Bot },
  ];
  const active = steps[step]; const Icon = active.icon;
  return <section className="mx-auto my-16 max-w-6xl px-4"><div className="mb-7 text-center"><p className="text-xs font-bold uppercase tracking-[.16em] text-[hsl(var(--primary))]">See the system work</p><h2 className="mt-2 text-3xl font-black text-[hsl(var(--text-primary))]">From intention to momentum</h2></div><div className="grid overflow-hidden rounded-[28px] border border-[hsl(var(--border))] bg-[hsl(var(--card))] shadow-[var(--shadow-md)] lg:grid-cols-[.82fr_1.18fr]">
    <div className="border-b border-[hsl(var(--border))] p-4 lg:border-b-0 lg:border-r"><div className="space-y-2">{steps.map((item,i)=><button key={item.title} onClick={()=>setStep(i)} className={`flex w-full items-center gap-3 rounded-2xl p-4 text-left transition-all duration-200 ${step===i?"bg-[hsl(var(--secondary))] text-[hsl(var(--primary))]":"hover:bg-[hsl(var(--background-subtle))]"}`}><span className="grid h-8 w-8 place-items-center rounded-full border border-current text-xs font-black">{i+1}</span><span><b className="block text-sm">{item.title}</b><span className="text-xs text-[hsl(var(--text-secondary))]">{item.text}</span></span></button>)}</div></div>
    <div className="relative min-h-[340px] bg-[linear-gradient(135deg,hsl(var(--primary)/.08),transparent)] p-8"><AnimatePresence mode="wait"><motion.div key={step} initial={reduced?false:{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}} transition={transition} className="mx-auto max-w-md"><div className="mb-6 flex items-center justify-between"><span className="rounded-full bg-[hsl(var(--primary))] px-3 py-1 text-xs font-bold text-white">Live mission</span><span className="text-xs text-[hsl(var(--text-secondary))]">Step {step+1} of 4</span></div><div className="rounded-3xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-6 shadow-[var(--shadow-lg)]"><Icon className="h-7 w-7 text-[hsl(var(--primary))]"/><h3 className="mt-5 text-2xl font-black text-[hsl(var(--text-primary))]">{active.title}</h3><p className="mt-2 text-[hsl(var(--text-secondary))]">{active.text}</p><div className="mt-6 h-2 overflow-hidden rounded-full bg-[hsl(var(--muted))]"><motion.div className="h-full bg-[hsl(var(--primary))]" initial={{width:0}} animate={{width:`${(step+1)*25}%`}} transition={transition}/></div></div></motion.div></AnimatePresence></div>
  </div></section>;
}

export function SolutionsJourney() {
  const options=[{name:"Professional",icon:BriefcaseBusiness,outcome:"A career plan that adapts weekly",metric:"6 hrs saved / week"},{name:"Student",icon:GraduationCap,outcome:"A portfolio-ready learning journey",metric:"3× clearer priorities"},{name:"Founder",icon:Building2,outcome:"Vision translated into accountable execution",metric:"42% less planning time"},{name:"Family",icon:Users,outcome:"Shared goals without coordination chaos",metric:"1 connected plan"}];
  const [active,setActive]=useState(0); const current=options[active]; const Icon=current.icon;
  return <section className="mx-auto my-14 max-w-6xl px-4"><div className="rounded-[28px] border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-6 shadow-[var(--shadow-sm)] sm:p-8"><div className="flex flex-wrap gap-2">{options.map((o,i)=><button key={o.name} onClick={()=>setActive(i)} className={`rounded-full px-4 py-2 text-sm font-bold transition-all duration-200 ${i===active?"bg-[hsl(var(--primary))] text-white shadow-md":"border border-[hsl(var(--border))] hover:-translate-y-0.5 hover:bg-[hsl(var(--secondary))]"}`}>{o.name}</button>)}</div><div className="mt-8 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-[hsl(var(--background-subtle))] p-5"><Icon className="h-6 w-6 text-[hsl(var(--primary))]"/><p className="mt-4 text-xs font-bold uppercase tracking-wider text-[hsl(var(--text-secondary))]">Your context</p><h3 className="mt-1 text-xl font-black">{current.name}</h3></div>{["AI structures your mission","LifeKit keeps execution moving"].map((x,i)=><div key={x} className="relative rounded-2xl border border-[hsl(var(--border))] p-5"><span className="text-xs font-black text-[hsl(var(--primary))]">0{i+2}</span><p className="mt-3 font-bold">{x}</p><ArrowRight className="absolute right-4 top-4 h-4 w-4 text-[hsl(var(--text-secondary))]"/></div>)}</div><div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-[hsl(var(--primary))] p-5 text-white"><b>{current.outcome}</b><span className="rounded-full bg-white/15 px-3 py-1 text-sm">{current.metric}</span></div></div></section>;
}

const providers=[{name:"CareerStack",cat:"Career",tag:"1-on-1 career coaching",rating:"4.9"},{name:"MoneyMentor",cat:"Finance",tag:"Savings and investment planning",rating:"4.8"},{name:"FitForge",cat:"Health",tag:"Science-backed fitness plans",rating:"4.9"},{name:"LearnWithPro",cat:"Education",tag:"Expert-led certification paths",rating:"4.7"}];
export function MarketplaceFinder(){const [q,setQ]=useState("");const [cat,setCat]=useState("All");const filtered=useMemo(()=>providers.filter(p=>(cat==="All"||p.cat===cat)&&`${p.name} ${p.tag}`.toLowerCase().includes(q.toLowerCase())),[q,cat]);return <section className="mx-auto my-12 max-w-6xl px-4"><div className="rounded-[28px] border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-5 shadow-[var(--shadow-md)] sm:p-7"><div className="flex flex-col gap-3 sm:flex-row"><label className="flex flex-1 items-center gap-2 rounded-xl border border-[hsl(var(--border))] px-4"><Search className="h-4 w-4"/><input className="h-12 flex-1 bg-transparent outline-none" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search providers, services or goals…"/></label><div className="flex gap-2 overflow-x-auto">{["All","Career","Finance","Health","Education"].map(x=><button key={x} onClick={()=>setCat(x)} className={`rounded-xl px-4 text-sm font-bold ${cat===x?"bg-[hsl(var(--primary))] text-white":"bg-[hsl(var(--background-subtle))]"}`}>{x}</button>)}</div></div><motion.div layout className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{filtered.map(p=><motion.article layout key={p.name} className="marketing-premium-card rounded-2xl border border-[hsl(var(--border))] p-4"><div className="flex items-center justify-between"><span className="rounded-full bg-[hsl(var(--secondary))] px-2 py-1 text-xs font-bold text-[hsl(var(--primary))]">Verified</span><span className="text-xs">★ {p.rating}</span></div><h3 className="mt-5 font-black">{p.name}</h3><p className="mt-1 text-sm text-[hsl(var(--text-secondary))]">{p.tag}</p><button className="mt-5 flex items-center gap-1 text-sm font-bold text-[hsl(var(--primary))]">Preview match <ArrowRight className="h-4 w-4"/></button></motion.article>)}</motion.div></div></section>}

export function PricingPlanner(){const [annual,setAnnual]=useState(true);const [missions,setMissions]=useState(8);const saving=annual?Math.round(499*12*.2):0;return <section className="mx-auto mb-10 max-w-6xl px-4"><div className="grid gap-4 rounded-[28px] border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-6 shadow-[var(--shadow-md)] md:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-wider text-[hsl(var(--primary))]">Plan your investment</p><h2 className="mt-2 text-2xl font-black">Make the value visible</h2><div className="mt-6 inline-flex rounded-full bg-[hsl(var(--background-subtle))] p-1"><button onClick={()=>setAnnual(false)} className={`rounded-full px-4 py-2 text-sm ${!annual?"bg-[hsl(var(--card))] shadow-sm":""}`}>Monthly</button><button onClick={()=>setAnnual(true)} className={`rounded-full px-4 py-2 text-sm ${annual?"bg-[hsl(var(--primary))] text-white shadow-sm":""}`}>Annual · save 20%</button></div><label className="mt-7 block text-sm font-bold">Active missions: {missions}<input type="range" min="1" max="20" value={missions} onChange={e=>setMissions(+e.target.value)} className="mt-3 w-full accent-[hsl(var(--primary))]"/></label></div><div className="rounded-2xl bg-[hsl(var(--primary))] p-6 text-white"><p className="text-sm text-white/70">Recommended</p><h3 className="mt-1 text-3xl font-black">{missions>10?"LifeKit Pro":"LifeKit Plus"}</h3><p className="mt-6 text-4xl font-black">₹{missions>10?(annual?799:999):(annual?399:499)}<span className="text-sm font-medium text-white/70"> / month</span></p><div className="mt-6 flex items-center gap-2 text-sm"><Check className="h-4 w-4"/> {annual?`Save ₹${saving} each year`:"Switch anytime"}</div></div></div></section>}

export function EnterpriseFlow(){const [active,setActive]=useState(0);const stages=["Identity & SSO","Private AI layer","Governance controls","Mission analytics"];return <section className="mx-auto my-14 max-w-6xl px-4"><div className="grid gap-6 rounded-[28px] bg-[#0d1711] p-6 text-white shadow-xl lg:grid-cols-[.8fr_1.2fr] sm:p-8"><div><ShieldCheck className="h-8 w-8 text-emerald-400"/><h2 className="mt-5 text-3xl font-black">Enterprise-ready by design</h2><p className="mt-3 text-white/60">Explore how LifeKit fits securely into your organisation.</p><div className="mt-7 space-y-2">{stages.map((s,i)=><button onClick={()=>setActive(i)} key={s} className={`flex w-full items-center gap-3 rounded-xl p-3 text-left text-sm font-bold transition-colors ${active===i?"bg-white/12 text-emerald-300":"text-white/60 hover:bg-white/5"}`}><span>{i+1}</span>{s}</button>)}</div></div><div className="relative grid min-h-[330px] place-items-center overflow-hidden rounded-2xl border border-white/10 bg-white/[.035]"><div className="absolute h-64 w-64 rounded-full border border-emerald-400/20"/><div className="absolute h-44 w-44 rounded-full border border-emerald-400/30"/><AnimatePresence mode="wait"><motion.div key={active} initial={{opacity:0,scale:.94}} animate={{opacity:1,scale:1}} exit={{opacity:0,scale:1.04}} transition={transition} className="relative z-10 max-w-xs rounded-2xl border border-white/15 bg-[#14251a] p-6 text-center shadow-2xl"><p className="text-xs font-bold uppercase tracking-widest text-emerald-400">Layer {active+1}</p><h3 className="mt-3 text-xl font-black">{stages[active]}</h3><p className="mt-3 text-sm text-white/60">Controlled access, visible data boundaries and clear administration at every layer.</p></motion.div></AnimatePresence></div></div></section>}
