import { ApiProperty } from '@nestjs/swagger';
import { AgentType } from './agent-request.dto';

export class AgentResponseDto {
  @ApiProperty({ description: 'The type of AI agent that processed the request', enum: AgentType, example: AgentType.COACH })
  agentType!: AgentType;

  @ApiProperty({ description: 'Flag indicating execution status success', example: true })
  success!: boolean;

  @ApiProperty({ description: 'The textual output generated by the AI agent', example: 'Based on your workout inputs, you are recovering well but should add 1 extra rest day.' })
  output!: string;

  @ApiProperty({ description: 'Metadata and contextual response parameters returned by the AI run', example: { tokenCount: 412, engineUsed: 'gemini-3.5-flash' } })
  metadata!: Record<string, any>;
}
