// ============================================================
// LifeKit Mock Data – used until APIs are connected
// ============================================================
import type { Mission } from "@/types/mission";
import type { Task } from "@/types/task";
import type { AiRecommendation } from "@/types/ai";
import type { Opportunity } from "@/types/opportunity";
import type { Memory } from "@/types/memory";
import type { Notification } from "@/types/notification";
import type { MarketplaceListing } from "@/types/marketplace";
import type { User } from "@/types/user";
import type { UserAnalytics } from "@/types/analytics";

export const MOCK_USER: User = {
  id: "user-1",
  fullName: "Arjun Sharma",
  email: "arjun@example.com",
  phone: "+91 98765 43210",
  avatarUrl: undefined,
  userType: "professional",
  location: "Bengaluru, India",
  bio: "Software engineer passionate about AI and building meaningful products.",
  focusAreas: ["career", "finance", "health"],
  skills: [
    { name: "JavaScript", level: "advanced" },
    { name: "React", level: "advanced" },
    { name: "Python", level: "intermediate" },
  ],
  interests: ["Technology", "Startups", "Fitness", "Reading"],
  careerInfo: {
    currentRole: "Software Engineer",
    company: "TechCorp",
    industry: "Technology",
    yearsOfExperience: 3,
    education: "B.Tech Computer Science",
  },
  preferences: {
    learningStyle: "hands-on",
    weeklyAvailableHours: 15,
    budgetRange: { min: 0, max: 10000, currency: "INR" },
    notificationPreference: "important",
    theme: "light",
    language: "en",
    timezone: "Asia/Kolkata",
    dateFormat: "DD/MM/YYYY",
    aiResponseStyle: "balanced",
    recommendationFrequency: "weekly",
    planningDepth: "standard",
    memoryEnabled: true,
  },
  personalGoals: ["Become an AI engineer", "Save ₹5 Lakh", "Run a half marathon"],
  isEmailVerified: true,
  isTwoFactorEnabled: false,
  createdAt: "2024-01-15T10:00:00Z",
  updatedAt: "2025-07-20T08:00:00Z",
  role: "user",
  subscriptionPlan: "plus",
  onboardingCompleted: true,
};

export const MOCK_MISSIONS: Mission[] = [
  {
    id: "mission-1",
    userId: "user-1",
    title: "Become a Software Engineer",
    description: "Transition from current role to a senior software engineer position at a top tech company.",
    goal: "Land a senior software engineering role within 6 months",
    category: "career",
    status: "active",
    progress: 42,
    priority: "high",
    targetDate: "2026-01-31",
    estimatedDurationWeeks: 24,
    budgetAmount: 25000,
    budgetCurrency: "INR",
    weeklyAvailableHours: 15,
    milestones: [
      {
        id: "ms-1",
        missionId: "mission-1",
        title: "Learn Python, DSA and GitHub",
        description: "Master Python fundamentals, data structures, algorithms, and Git workflows",
        status: "completed",
        progress: 100,
        startDate: "2025-08-01",
        endDate: "2025-08-31",
        tasks: [],
        resources: [],
        dependencies: [],
        order: 1,
      },
      {
        id: "ms-2",
        missionId: "mission-1",
        title: "Learn Machine Learning Fundamentals",
        description: "Study ML algorithms, libraries and build a foundational understanding",
        status: "in-progress",
        progress: 60,
        startDate: "2025-09-01",
        endDate: "2025-09-30",
        tasks: [],
        resources: [],
        dependencies: ["ms-1"],
        order: 2,
      },
      {
        id: "ms-3",
        missionId: "mission-1",
        title: "Build Portfolio Projects",
        description: "Create 3 end-to-end projects demonstrating ML and software skills",
        status: "pending",
        progress: 0,
        startDate: "2025-10-01",
        endDate: "2025-10-31",
        tasks: [],
        resources: [],
        dependencies: ["ms-2"],
        order: 3,
      },
    ],
    successMetrics: [
      { id: "sm-1", description: "Receive 2+ interview calls per week", measurable: true, achieved: false },
      { id: "sm-2", description: "Complete 3 portfolio projects", measurable: true, achieved: false },
      { id: "sm-3", description: "Get a job offer from a top-tier company", measurable: true, achieved: false },
    ],
    risks: [
      { id: "r-1", description: "Time constraints due to current job", severity: "medium", mitigation: "Block 2 hours daily for learning" },
    ],
    resources: [],
    currentMilestoneId: "ms-2",
    nextTaskTitle: "Complete the React advanced patterns module",
    tags: ["tech", "career", "learning"],
    isPersonal: true,
    createdAt: "2025-08-01T10:00:00Z",
    updatedAt: "2025-07-20T08:00:00Z",
  },
  {
    id: "mission-2",
    userId: "user-1",
    title: "Save ₹5 Lakh Emergency Fund",
    description: "Build a 6-month emergency fund to achieve financial stability.",
    goal: "Save ₹5,00,000 in a high-yield savings account",
    category: "finance",
    status: "active",
    progress: 28,
    priority: "high",
    targetDate: "2026-06-30",
    estimatedDurationWeeks: 52,
    budgetAmount: 500000,
    budgetCurrency: "INR",
    weeklyAvailableHours: 2,
    milestones: [
      {
        id: "ms-4",
        missionId: "mission-2",
        title: "Set up automated savings",
        description: "Open a high-yield account and set up auto-debit",
        status: "completed",
        progress: 100,
        startDate: "2025-01-01",
        endDate: "2025-01-15",
        tasks: [],
        resources: [],
        dependencies: [],
        order: 1,
      },
    ],
    successMetrics: [
      { id: "sm-4", description: "Balance reaches ₹5,00,000", measurable: true, achieved: false },
    ],
    risks: [],
    resources: [],
    currentMilestoneId: "ms-4",
    nextTaskTitle: "Review monthly budget and identify savings opportunities",
    tags: ["finance", "savings"],
    isPersonal: true,
    createdAt: "2025-01-01T10:00:00Z",
    updatedAt: "2025-07-20T08:00:00Z",
  },
  {
    id: "mission-3",
    userId: "user-1",
    title: "Improve Fitness & Run Half Marathon",
    description: "Train consistently and complete a half marathon within the year.",
    goal: "Complete a 21km half marathon under 2.5 hours",
    category: "health",
    status: "active",
    progress: 35,
    priority: "medium",
    targetDate: "2025-12-15",
    estimatedDurationWeeks: 20,
    weeklyAvailableHours: 5,
    milestones: [],
    successMetrics: [
      { id: "sm-5", description: "Complete half marathon under 2:30", measurable: true, achieved: false },
    ],
    risks: [],
    resources: [],
    nextTaskTitle: "Complete today's 8km training run",
    tags: ["health", "fitness"],
    isPersonal: true,
    createdAt: "2025-06-01T10:00:00Z",
    updatedAt: "2025-07-20T08:00:00Z",
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: "task-1",
    userId: "user-1",
    missionId: "mission-1",
    missionTitle: "Become a Software Engineer",
    milestoneId: "ms-2",
    milestoneTitle: "Learn Machine Learning Fundamentals",
    title: "Complete React advanced patterns module",
    description: "Finish the advanced React patterns course on the learning platform",
    status: "in-progress",
    priority: "high",
    dueDate: "2025-07-28",
    dueTime: "18:00",
    estimatedDurationMinutes: 120,
    dependencies: [],
    notes: [],
    resources: [{ id: "r-1", title: "Advanced React Patterns", url: "https://example.com", type: "course" }],
    tags: ["react", "learning"],
    order: 1,
    createdAt: "2025-07-20T10:00:00Z",
    updatedAt: "2025-07-20T10:00:00Z",
  },
  {
    id: "task-2",
    userId: "user-1",
    missionId: "mission-1",
    missionTitle: "Become a Software Engineer",
    title: "Review two recommended internship listings",
    description: "Browse and evaluate internship opportunities matched by AI",
    status: "not-started",
    priority: "medium",
    dueDate: "2025-07-28",
    estimatedDurationMinutes: 30,
    dependencies: [],
    notes: [],
    resources: [],
    tags: ["career", "internship"],
    order: 2,
    createdAt: "2025-07-20T10:00:00Z",
    updatedAt: "2025-07-20T10:00:00Z",
  },
  {
    id: "task-3",
    userId: "user-1",
    missionId: "mission-2",
    missionTitle: "Save ₹5 Lakh Emergency Fund",
    title: "Review monthly budget and identify savings opportunities",
    description: "Analyse last month's expenses and find areas to save more",
    status: "not-started",
    priority: "high",
    dueDate: "2025-07-28",
    estimatedDurationMinutes: 45,
    dependencies: [],
    notes: [],
    resources: [],
    tags: ["finance", "budget"],
    order: 3,
    createdAt: "2025-07-20T10:00:00Z",
    updatedAt: "2025-07-20T10:00:00Z",
  },
  {
    id: "task-4",
    userId: "user-1",
    missionId: "mission-3",
    missionTitle: "Improve Fitness & Run Half Marathon",
    title: "Complete today's 8km training run",
    description: "Easy-paced 8km run as per training plan",
    status: "not-started",
    priority: "medium",
    dueDate: "2025-07-28",
    dueTime: "06:30",
    estimatedDurationMinutes: 60,
    dependencies: [],
    notes: [],
    resources: [],
    tags: ["fitness", "running"],
    order: 4,
    createdAt: "2025-07-20T10:00:00Z",
    updatedAt: "2025-07-20T10:00:00Z",
  },
];

export const MOCK_RECOMMENDATIONS: AiRecommendation[] = [
  {
    id: "rec-1",
    userId: "user-1",
    title: "React & TypeScript Masterclass",
    description: "Comprehensive course covering React 18, TypeScript, Next.js and modern patterns.",
    category: "education",
    type: "learning",
    provider: "Udemy",
    relatedMissionId: "mission-1",
    relatedMissionTitle: "Become a Software Engineer",
    matchScore: 94,
    cost: 499,
    currency: "INR",
    rating: 4.8,
    imageUrl: undefined,
    url: "https://example.com/course",
    reasons: ["Aligns with your software engineer mission", "Matches your current milestone: ML fundamentals", "Within your budget"],
    isSaved: false,
    isDismissed: false,
    createdAt: "2025-07-20T10:00:00Z",
  },
  {
    id: "rec-2",
    userId: "user-1",
    title: "Career Mentor – Senior Engineer at Google",
    description: "1-on-1 mentoring sessions with a senior engineer who helps with interview prep.",
    category: "career",
    type: "expert",
    provider: "MentorKit",
    relatedMissionId: "mission-1",
    relatedMissionTitle: "Become a Software Engineer",
    matchScore: 87,
    cost: 2000,
    currency: "INR",
    rating: 4.9,
    reasons: ["Directly supports your career mission", "Expert in the exact role you're targeting"],
    isSaved: true,
    isDismissed: false,
    createdAt: "2025-07-20T10:00:00Z",
  },
];

export const MOCK_OPPORTUNITIES: Opportunity[] = [
  {
    id: "opp-1",
    title: "Software Engineering Intern",
    organisation: "Razorpay",
    type: "internship",
    category: "career",
    location: "Bengaluru, India",
    isRemote: false,
    deadline: "2025-08-15",
    eligibilitySummary: "Final year students or recent graduates with React/Node.js experience",
    description: "Join Razorpay's engineering team as a software engineering intern. Work on real products used by millions.",
    requirements: [
      { label: "React.js experience", description: "1+ year of React development" },
      { label: "Node.js knowledge", description: "Basic backend development" },
    ],
    requiredDocuments: ["Resume", "GitHub profile link", "Portfolio"],
    applicationUrl: "https://razorpay.com/careers",
    experienceLevel: "entry",
    matchScore: 91,
    relatedMissionId: "mission-1",
    relatedMissionTitle: "Become a Software Engineer",
    matchReasons: ["Matches your career mission", "Location matches your preference", "Tech stack aligns with your skills"],
    isSaved: false,
    isDismissed: false,
    applicationStatus: "not-applied",
    tags: ["engineering", "internship", "fintech"],
    postedAt: "2025-07-15T10:00:00Z",
    updatedAt: "2025-07-20T10:00:00Z",
  },
];

export const MOCK_MEMORIES: Memory[] = [
  {
    id: "mem-1",
    userId: "user-1",
    content: "Prefers hands-on learning over reading theory. Learns best through building projects.",
    category: "preference",
    relatedMissionId: "mission-1",
    relatedMissionTitle: "Become a Software Engineer",
    source: "ai",
    importance: "high",
    isPinned: true,
    isArchived: false,
    lastUsedAt: "2025-07-20T10:00:00Z",
    createdAt: "2025-07-01T10:00:00Z",
    updatedAt: "2025-07-20T10:00:00Z",
    tags: ["learning", "preference"],
  },
  {
    id: "mem-2",
    userId: "user-1",
    content: "Available 15 hours per week for mission work — mostly evenings and weekends.",
    category: "constraint",
    source: "user",
    importance: "high",
    isPinned: false,
    isArchived: false,
    lastUsedAt: "2025-07-15T10:00:00Z",
    createdAt: "2025-07-01T10:00:00Z",
    updatedAt: "2025-07-15T10:00:00Z",
    tags: ["time", "availability"],
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "notif-1",
    userId: "user-1",
    type: "task-reminder",
    title: "Task Due Today",
    message: "Complete React advanced patterns module is due today by 6:00 PM",
    isRead: false,
    actionUrl: "/tasks",
    relatedMissionId: "mission-1",
    createdAt: "2025-07-27T08:00:00Z",
  },
  {
    id: "notif-2",
    userId: "user-1",
    type: "opportunity-match",
    title: "New Opportunity Match",
    message: "A new internship at Razorpay matches your Software Engineer mission (91% match)",
    isRead: false,
    actionUrl: "/opportunities/opp-1",
    createdAt: "2025-07-27T07:30:00Z",
  },
  {
    id: "notif-3",
    userId: "user-1",
    type: "milestone-completion",
    title: "Milestone Completed!",
    message: "You completed 'Learn Python, DSA and GitHub' — great work!",
    isRead: true,
    relatedMissionId: "mission-1",
    createdAt: "2025-07-26T18:00:00Z",
  },
];

export const MOCK_MARKETPLACE_LISTINGS: MarketplaceListing[] = [
  {
    id: "listing-1",
    title: "Full-Stack Web Development Bootcamp",
    slug: "full-stack-bootcamp",
    type: "course",
    category: "education",
    provider: {
      id: "prov-1",
      name: "CodeAcademy Pro",
      rating: 4.8,
      reviewCount: 1240,
      verified: true,
      badges: ["Top Provider", "Certified"],
      responseTime: "< 2 hours",
    },
    description: "A comprehensive 12-week bootcamp covering React, Node.js, databases, and deployment.",
    shortDescription: "12-week full-stack bootcamp with job placement support",
    images: [],
    features: [
      { label: "Live mentoring sessions", included: true },
      { label: "Project-based curriculum", included: true },
      { label: "Job placement assistance", included: true },
      { label: "Certificate on completion", included: true },
    ],
    pricingTiers: [
      {
        id: "tier-1",
        name: "Standard",
        price: 15000,
        currency: "INR",
        billingCycle: "one-time",
        features: ["12 weeks access", "Community support"],
        isPopular: false,
      },
      {
        id: "tier-2",
        name: "Premium",
        price: 25000,
        currency: "INR",
        billingCycle: "one-time",
        features: ["12 weeks access", "1-on-1 mentoring", "Job placement"],
        isPopular: true,
      },
    ],
    basePrice: 15000,
    currency: "INR",
    rating: 4.8,
    reviewCount: 1240,
    reviews: [],
    deliveryMode: "online",
    duration: "12 weeks",
    tags: ["web development", "react", "node.js"],
    relatedMissionCategories: ["career", "education"],
    isFeatured: true,
    isPopular: true,
    isSaved: false,
    createdAt: "2025-01-01T10:00:00Z",
    updatedAt: "2025-07-20T10:00:00Z",
  },
];

export const MOCK_ANALYTICS: UserAnalytics = {
  missionCompletionRate: 33,
  taskCompletionRate: 68,
  activeMissions: 3,
  completedMissions: 1,
  completedMilestones: 4,
  totalTasksCompleted: 47,
  weeklyProductivity: [
    { day: "Mon", tasksCompleted: 3, minutesWorked: 90 },
    { day: "Tue", tasksCompleted: 2, minutesWorked: 60 },
    { day: "Wed", tasksCompleted: 4, minutesWorked: 120 },
    { day: "Thu", tasksCompleted: 1, minutesWorked: 30 },
    { day: "Fri", tasksCompleted: 3, minutesWorked: 90 },
    { day: "Sat", tasksCompleted: 5, minutesWorked: 150 },
    { day: "Sun", tasksCompleted: 2, minutesWorked: 60 },
  ],
  progressOverTime: [
    { date: "2025-06-01", planned: 10, actual: 8 },
    { date: "2025-06-15", planned: 25, actual: 20 },
    { date: "2025-07-01", planned: 40, actual: 35 },
    { date: "2025-07-15", planned: 55, actual: 42 },
    { date: "2025-07-27", planned: 65, actual: 50 },
  ],
  categoryProgress: [
    { category: "career", completedMissions: 0, activeMissions: 1, completionRate: 42 },
    { category: "finance", completedMissions: 0, activeMissions: 1, completionRate: 28 },
    { category: "health", completedMissions: 1, activeMissions: 1, completionRate: 35 },
  ],
  taskStatusDistribution: {
    notStarted: 12,
    inProgress: 5,
    blocked: 2,
    completed: 47,
    skipped: 3,
  },
  milestoneTimeline: [
    {
      milestoneTitle: "Learn Python, DSA and GitHub",
      missionTitle: "Become a Software Engineer",
      plannedDate: "2025-08-31",
      actualDate: "2025-08-28",
      status: "completed",
    },
  ],
  currentStreak: 5,
  longestStreak: 12,
  averageDelayDays: 1.8,
  recommendedFocusAreas: ["Complete ML milestone", "Review financial savings plan"],
};
